// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp4.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231207013424_AddEClientEOrder")]
    partial class AddEClientEOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataModel.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasDiscriminator<string>("ClientType").HasValue("Regular");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Addr1",
                            Name = "Andrzej"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Addr2",
                            Name = "Marcin"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Addr3",
                            Name = "Tomasz"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Addr4",
                            Name = "Marian"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Addr5",
                            Name = "Janusz"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Addr6",
                            Name = "Agnieszka"
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "Addr7",
                            Name = "Katarzyna"
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "Addr8",
                            Name = "Maja"
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "Addr9",
                            Name = "Grzegorz"
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "Addr10",
                            Name = "Michalina"
                        });
                });

            modelBuilder.Entity("DataModel.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("OrderType").HasValue("Regular");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataModel.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DataModel.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataModel.EClient", b =>
                {
                    b.HasBaseType("DataModel.Client");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Online");
                });

            modelBuilder.Entity("DataModel.EOrder", b =>
                {
                    b.HasBaseType("DataModel.Order");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Online");
                });

            modelBuilder.Entity("DataModel.Order", b =>
                {
                    b.HasOne("DataModel.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataModel.OrderItem", b =>
                {
                    b.HasOne("DataModel.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DataModel.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DataModel.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
