ICON_SIZE = 50
MAP_Y_OFFSET = 1
ACTION_COOLDOWN = 1
MULTIPLIFICATION_COOLDOWN = 9

# ANIMALS
ANIMAL_DEFAULT_MOVE_RANGE = 1

SHEEP_STRENGTH = 4
SHEEP_INITIATIVE = 4

FOX_STRENGTH = 3
FOX_INITIATIVE = 7

TORTOISE_STRENGTH = 2
TORTOISE_INITIATIVE = 1
TORTOISE_MOVE_PROBABILITY = 0.25
TORTOISE_DEFENSE = 5

WOLF_STRENGTH = 9
WOLF_INITIATIVE = 5

ANTELOPE_STRENGTH = 4
ANTELOPE_INITIATIVE = 4
ANTELOPE_ESCAPE_PROBABILITY = 0.5

CYBER_SHEEP_STRENGTH = 11
CYBER_SHEEP_INITIATIVE = 4

# PLANTS
PLANT_BREEDING_COOLDOWN = 5
PLANT_MULTIPLIFICATION_ATTEMPTS = 1
PLANT_MULTIPLIFICATION_PROBABILITY = 0.05

GRASS_STRENGTH = 0

DANDELION_STRENGTH = 0
DANDELION_MULTIPLIFICATION_ATTEMPTS = 3

GUARANA_STRENGTH = 0
GUARANA_STRENGTH_BOOST = 3

WOLFBERRY_STRENGTH = 99

HOGWEED_STRENGTH = 10
HOGWEED_POISON_RADIUS = 1

# HUMAN

HUMAN_STRENGTH = 5
HUMAN_INITIATIVE = 4
HUMAN_ABILITY_COOLDOWN = 5
HUMAN_ABILITY_ACTIVE_TIME = 5
HUMAN_ABILITY_FULLY_ACTIVE = 3
HUMAN_ABILITY_HALF_ACTIVE = 2
HUMAN_ABILITY_MOVE_RANGE = 2
